// Code generated by counterfeiter. DO NOT EDIT.
package pkgfakes

import (
	"sync"
	"vmware-samples/concourse-resource-for-marketplace/m/v2/pkg"
)

type FakeMkpcliRunner struct {
	Stub        func(*pkg.Input, ...string) pkg.Command
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 *pkg.Input
		arg2 []string
	}
	returns struct {
		result1 pkg.Command
	}
	returnsOnCall map[int]struct {
		result1 pkg.Command
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMkpcliRunner) Spy(arg1 *pkg.Input, arg2 ...string) pkg.Command {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 *pkg.Input
		arg2 []string
	}{arg1, arg2})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("MkpcliRunner", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *FakeMkpcliRunner) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeMkpcliRunner) Calls(stub func(*pkg.Input, ...string) pkg.Command) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeMkpcliRunner) ArgsForCall(i int) (*pkg.Input, []string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeMkpcliRunner) Returns(result1 pkg.Command) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 pkg.Command
	}{result1}
}

func (fake *FakeMkpcliRunner) ReturnsOnCall(i int, result1 pkg.Command) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 pkg.Command
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 pkg.Command
	}{result1}
}

func (fake *FakeMkpcliRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMkpcliRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.MkpcliRunner = new(FakeMkpcliRunner).Spy
